insert into banks (bankname, bankcode, swiftcode) values('AEON Bank,Ltd.', 40, null);
insert into banks (bankname, bankcode, swiftcode) values('Aozora Bank,Ltd.', 398, 'NCBTJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Aozora Trust Bank,Ltd.', 310, null);
insert into banks (bankname, bankcode, swiftcode) values('Bank of Japan', 0, 'BOJPJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Chuo Mitsui Asset Trust and Banking Co.,Ltd.', 315, null);
insert into banks (bankname, bankcode, swiftcode) values('eBANK Corporation', 36, null);
insert into banks (bankname, bankcode, swiftcode) values('First Bank of Toyama,Ltd.', 534, 'FBTYJPJ1');
insert into banks (bankname, bankcode, swiftcode) values('Fukushima Bank', 513, null);
insert into banks (bankname, bankcode, swiftcode) values('Incubator Bank of Japan,Ltd.', 37, null);
insert into banks (bankname, bankcode, swiftcode) values('JSF Trust and Banking Co.,Ltd.', 321, null);
insert into banks (bankname, bankcode, swiftcode) values('Kansai Urban Banking Corporation', 554, 'KSBJJPJS');
insert into banks (bankname, bankcode, swiftcode) values('Kirayaka Bank,Ltd.', 508, 'SHIAJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Minami Nippon Bank,Ltd.', 594, null);
insert into banks (bankname, bankcode, swiftcode) values('Mitsubishi UFJ Trust and Banking Corporation', 288, 'MTBCJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Mizuho Bank,Ltd.Osaka', 1, 'MHBKJPJS');
insert into banks (bankname, bankcode, swiftcode) values('Mizuho Trust and Banking Co.,Ltd.', 289, 'YTBCJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Nagano Bank,Ltd.', 533, 'NAGAJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('NikkoCiti Trust and Banking Corporation', 306, 'NKTBJPJTOTK');
insert into banks (bankname, bankcode, swiftcode) values('Okinawa Kaiho Bank', 596, 'OKWAJPJ1');
insert into banks (bankname, bankcode, swiftcode) values('ORIX Trust and Banking Corporation', 307, null);
insert into banks (bankname, bankcode, swiftcode) values('Resona Bank,Ltd.,Osaka', 10, 'DIWAJPJS');
insert into banks (bankname, bankcode, swiftcode) values('Resona TrustÅïBanking Co.,Ltd.', 326, null);
insert into banks (bankname, bankcode, swiftcode) values('Seven Bank,Ltd.', 34, null);
insert into banks (bankname, bankcode, swiftcode) values('ShinGinko Tokyo,Ltd.', 322, 'SGTKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Shinkin Trust Bank,Ltd.', 309, 'SKTBJPJ1');
insert into banks (bankname, bankcode, swiftcode) values('Shinsei TrustÅïBanking Co.,Ltd.', 320, null);
insert into banks (bankname, bankcode, swiftcode) values('Sony Bank Inc.', 35, 'SONYJPJ1');
insert into banks (bankname, bankcode, swiftcode) values('The 77 Bank,Ltd.', 125, 'BOSSJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Akita Bank,Ltd.', 119, 'AKITJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Aomori Bank,Ltd.', 117, 'AOMBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Awa Bank,Ltd.', 172, 'AWABJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Fukuoka,Ltd.', 177, 'FKBKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Ikeda,Ltd.', 161, 'BIKEJPJS');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Iwate,Ltd.', 123, 'BAIWJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Kochi,Ltd.', 578, 'KOTIJOJT');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Nagasaki,Ltd.', 585, null);
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Nagoya,Ltd.', 543, 'NAGOJPJN');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Okinawa,Ltd.', 188, 'BOKIJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Bank of Saga,Ltd.', 179, 'BKSGJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Biwako Bank,Ltd.', 547, 'BIWAJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Chikuho Bank,Ltd.', 178, null);
insert into banks (bankname, bankcode, swiftcode) values('The Chukyo Bank,Ltd.', 544, 'CKBKJPJN');
insert into banks (bankname, bankcode, swiftcode) values('The Chuo Mitsui Trust and Banking Co.,Ltd.', 291, 'MTRBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Daishi Bank,Ltd.', 140, 'DAISJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Daito Bank,Ltd.', 514, null);
insert into banks (bankname, bankcode, swiftcode) values('The Ehime Bank,Ltd.', 576, 'HIMEJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Fukuho Bank,Ltd.', 537, 'FUHOJPJ1');
insert into banks (bankname, bankcode, swiftcode) values('The Fukui Bank,Ltd.', 147, 'FKUIJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Fukuoka Chuo Bank,Ltd.', 582, null);
insert into banks (bankname, bankcode, swiftcode) values('The Gifu Bank,Ltd.', 541, 'GIFBJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Gunma Bank,Ltd.', 128, 'GUMAJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Hachijuni Bank,Ltd.', 143, 'HABKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Higashi-Nippon Bank,Ltd.', 525, 'HNPBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Hokkaido Bank,Ltd.', 116, 'HKBKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Hokkoku Bank,Ltd.', 146, 'HKOKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Hokuetsu Bank,Ltd.', 141, 'HETSJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Hokuto Bank,Ltd.', 120, 'HOKBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Howa Bank,Ltd.', 590, null);
insert into banks (bankname, bankcode, swiftcode) values('The Hyakugo Bank,Ltd.', 155, 'HYKGJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Hyakujushi Bank,Ltd.', 173, 'HYAKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Ibaraki Bank,Ltd.', 519, null);
insert into banks (bankname, bankcode, swiftcode) values('The Japan Net Bank,Ltd.', 33, null);
insert into banks (bankname, bankcode, swiftcode) values('The Juroku Bank,Ltd.', 153, 'JUROJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Kagoshima Bank,Ltd.', 185, 'KAGOJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Kanagawa Bank,Ltd.', 530, null);
insert into banks (bankname, bankcode, swiftcode) values('The Kanto Tsukuba Bank,Ltd.', 131, 'KGBKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Keiyo Bank,Ltd.', 522, 'KEIBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Kinki Osaka Bank,Ltd.', 159, 'OSABJPJS');
insert into banks (bankname, bankcode, swiftcode) values('The Kita-Nippon Bank,Ltd.', 509, 'KNPBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Kiyo Bank,Ltd.', 163, 'KIYOJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Kumamoto Family Bank,Ltd', 587, 'KUMAJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Michinoku Bank,Ltd.', 118, 'MCHIJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Mie Bank,Ltd.', 154, 'MIEBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Miyazaki Bank,Ltd.', 184, 'MIYAJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Miyazaki Taiyo Bank,Ltd.', 591, null);
insert into banks (bankname, bankcode, swiftcode) values('The Nomura Trust and Banking Co.,Ltd.', 304, 'NMTBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Norinchukin Trust and Banking Co.,Ltd.', 311, 'NCTBJPJ1');
insert into banks (bankname, bankcode, swiftcode) values('The Ogaki Kyoritsu Bank,Ltd.', 152, 'OGAKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Oita Bank,Ltd.', 183, 'OITAJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Sagakyoei Bank,Ltd.', 583, null);
insert into banks (bankname, bankcode, swiftcode) values('The Saikyo Bank,Ltd.', 570, 'SAKBJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Sapporo Bank,Ltd.', 502, 'SAPBJPJP');
insert into banks (bankname, bankcode, swiftcode) values('The Sendai Bank,Ltd.', 512, null);
insert into banks (bankname, bankcode, swiftcode) values('The Senshu Bank,Ltd.', 160, 'SSBOJPJS');
insert into banks (bankname, bankcode, swiftcode) values('The Shikoku Bank,Ltd.', 175, 'SIKOJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Shimane Bank,Ltd.', 565, null);
insert into banks (bankname, bankcode, swiftcode) values('The Shimizu Bank,Ltd.', 151, 'SMZGJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Shinwa Bank,Ltd.', 181, 'SHWAJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Shizuoka Chuo Bank,Ltd.', 538, null);
insert into banks (bankname, bankcode, swiftcode) values('The Shonai Bank,Ltd.', 121, 'SNAIJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Sumitomo Trust and Banking Company,Ltd.', 294, 'STBCJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Taiko Bank,Ltd.', 532, null);
insert into banks (bankname, bankcode, swiftcode) values('The Taisho Bank,Ltd.', 555, null);
insert into banks (bankname, bankcode, swiftcode) values('The Tokushima Bank,Ltd.', 572, 'TKSBJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Tokyo Star Bank,Ltd.', 526, 'TSBKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Tottori Bank,Ltd.', 166, 'BIRDJPJZ');
insert into banks (bankname, bankcode, swiftcode) values('The Towa Bank,Ltd.', 516, 'TOWAJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Yachiyo Bank,Ltd.', 597, 'YACYJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Yamagata Bank,Ltd.', 122, 'YAMBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Yamaguchi Bank,Ltd.', 170, 'YMBKJPJT');
insert into banks (bankname, bankcode, swiftcode) values('The Yamanashi Chuo Bank,Ltd.', 142, 'YCHBJPJT');
insert into banks (bankname, bankcode, swiftcode) values('Tomato Bank,Ltd.', 566, 'TOMAJPJZ');
