defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: customers
  password: password
  host: localhost


development:
  <<: *defaults
  database: customers_development

test:
  <<: *defaults
  database: customers_test

production:
  <<: *defaults
  database: customers_production
